- title: Graduate Affairs Committee
  level: Department of Chemistry
  role: Chair
  when: "2025--"
- title: STEM Artificial Intelligence Search Committee
  level: College of Arts and Sciences
  role: Member
  when: 2024-25
  what: The CWRU College of Arts and Sciences formed a search committee
        to evaluate applications for two new faculty positions in the
        college, one focusing on AI Ethics and the other focusing on
        applications of AI in the sciences.
- title: Faculty Search Committee
  level: Department of Chemistry
  when: AY2024-25
  role: Chair
  what: Search committee to evaluate candidates in applications of
        AI/ML in computation-guided chemistry or drug discovery.
- title: Artificial Intelligence Screening Committee
  level: College of Arts and Sciences
  role: Member
  when: 2023-24
  what: The CWRU College of Arts and Sciences formed a search committee
        to evaluate applications for two new faculty positions in the
        college, one focusing on AI Ethics and the other focusing on
        applications of AI in the sciences.
- title: Graduate Program Review Committee
  level: Department of Chemistry
  role: Member
  when: Fall 2023
  what: The Department of CHemistry formed an ad hoc committee to conduct
        a self-study of the graduate programs offered by the department.
        I wrote the "Program Access" section.
- title: NSF CAREER Writing Workshop
  level: CWRU
  role: Panelist
  when: 2023
- title: CWRU Chemistry Research Symposium
  role: Co-founder and Co-organizer
  level: Department of Chemistry
  when: "2023--"
  what: CWRU Chemistry Research Symposium (C2RS) is a graduate student led
        symposium held annually to let students share their accomplishments.
        Winners are awarded with cash prizes. I co-founded and co-organized it
        with Prof. Metin Karayilan.
- title: Squire Scholarship Interview Panel
  level: College of Arts and Sciences
  when: 2023
  role: Panel Reviewer
  what: The College of Arts and Sciences formed a panel to review applications
        for the Squire Scholarship, a scholarship awarded to students who
        demonstrate academic excellence and leadership.
- title: Graduate Admissions Committee
  level: Department of Chemistry
  role: Member
  when: "2019--"
- title: Colloquium Committee
  level: Department of Chemistry
  when: "2019--2025"
  role: Co-chair
- title: Expanding Horizons Initiative
  level: College of Arts and Sciences
  when: 2023
  role: Panel Reviewer
- title: Faculty Search Committee
  level: Department of Chemistry
  when: AY2021-22
  role: Member
- title: Curriculum Committee
  level: College of Arts and Sciences
  when: Fall 2020 (Sabbatical Replacement)
  role: Member
- title: Chemistry Executive Committee
  level: Department of Chemistry
  when: "2019--2021"
  role: Member
